[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "cd web && npm install"
]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "python run_server.py"
